language: php
php:
    - '7.0'
    - '7.1'

before_script:
    - composer install --prefer-source

script:
    - mkdir -p build/logs
    - composer test

after_script:
    - travis_retry php vendor/bin/coveralls -v